# TESTING ENVS

In [ ]:
from myosuite.utils import gym
import skvideo.io
import numpy as np
import os

In [ ]:
from IPython.display import HTML
from base64 import b64encode
 
def show_video(video_path, video_width = 400):
   
  video_file = open(video_path, "r+b").read()
 
  video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
  return HTML(f"""<video autoplay width={video_width} controls><source src="{video_url}"></video>""")
 

In [ ]:
env = gym.make('myoHandWheelHoldFixed-v0')
print('Sites: ', [env.sim.model.site_name2id])

In [ ]:
env = gym.make('myoHandWheelHoldFixed-v0')
print('List of cameras available', [env.sim.model.camera(i).name for i in range(env.sim.model.ncam)])
env.reset()
frames = []
for _ in range(100):
    frame = env.sim.renderer.render_offscreen(
                        width=400,
                        height=400,
                        camera_id=0)
    frames.append(frame)
    env.step(env.action_space.sample()) # take a random action
env.close()

os.makedirs('videos', exist_ok=True)
# make a local copy
skvideo.io.vwrite('videos/temp.mp4', np.asarray(frames),outputdict={"-pix_fmt": "yuv420p"})

# show in the notebook
show_video('videos/temp.mp4')

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(frame)

# Python testing

In [21]:
import mujoco

In [22]:
model = mujoco.MjModel.from_xml_path("../assets/wheelchair/myowc_skeleton.xml")
data = mujoco.MjData(model)

In [23]:
model.ngeom

252

In [24]:
model.geom_rgba

array([[0.5 , 0.5 , 0.5 , 1.  ],
       [0.5 , 0.5 , 0.5 , 1.  ],
       [0.5 , 0.5 , 0.5 , 1.  ],
       ...,
       [0.8 , 0.7 , 0.5 , 1.  ],
       [0.8 , 0.7 , 0.5 , 1.  ],
       [0.89, 0.85, 0.98, 1.  ]], dtype=float32)

In [33]:
[model.geom(i).name for i in range(model.ngeom)]

['floor',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'right_rear_coll',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'left_rear_coll',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'pelvis_r',
 'pelvis_l',
 'pelvis_r_coll',
 'pelvis_l_coll',
 'sacrum1',
 'lumbar5',
 'lumbar4',
 'lumbar3',
 'lumbar2',
 'lumbar1',
 'thoracic12_s',
 'thoracic11_s',
 'thoracic10_s',
 'thoracic9_s',
 'thoracic8_s',
 'thoracic7_s',
 'thoracic6_s',
 'thoracic5_s',
 'thoracic4_s',
 'thoracic3_s',
 'thoracic2_s',
 'thoracic1_s',
 'thorax',
 'thorax_coll1',
 'thorax_coll2',
 'thorax_coll3',
 'cerv7',
 'cerv6',
 'cerv6_coll',
 'cerv5',
 'cerv5_coll',
 'cerv4',
 'cerv4_coll',
 'cerv3',
 'cerv3_coll',
 'cerv2',
 'cerv1',
 'hat_skull_coll',
 'skull',
 'jaw',
 'hat_jaw_coll2',
 'clavicle_r',
 'scapula_r',
 'humerus_r',
 'humerus_r_coll',
 'ulna_r',
 'ulna_r_coll',
 'radius_r_coll',
 'r

## `mjData`
`mjData` contains the *state* and quantities that depend on it. The state is made up of time, [generalized](https://en.wikipedia.org/wiki/Generalized_coordinates) positions and generalized velocities. These are respectively `data.time`, `data.qpos` and `data.qvel`. In order to make a new `mjData`, all we need is our `mjModel`

In [29]:
[model.site(i).name for i in range(model.nsite)]

['wheel',
 's_head',
 's_wrist_r',
 's_wrist_l',
 'r_foot_touch',
 'r_toes_touch',
 'l_foot_touch',
 'l_toes_touch']

In [40]:
print(data.site_xpos) #XYZ positions of sites listed above

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# JOINTS
print([model.jnt(i).name for i in range(model.njnt)])
print(model.njnt)

#joint position
print(data.qpos)
print(len(data.qpos))

#joint velocity
print(data.qvel)
print(len(data.qvel))

['wheelchair', 'right_rear', 'left_rear', 'right_fork', 'right_caster', 'left_fork', 'left_caster', 'sternoclavicular_r2_r', 'sternoclavicular_r3_r', 'unrotscap_r3_r', 'unrotscap_r2_r', 'acromioclavicular_r2_r', 'acromioclavicular_r3_r', 'acromioclavicular_r1_r', 'unrothum_r1_r', 'unrothum_r3_r', 'unrothum_r2_r', 'elv_angle_r', 'shoulder_elv_r', 'shoulder1_r2_r', 'shoulder_rot_r', 'elbow_flex_r', 'pro_sup', 'deviation', 'flexion_r', 'cmc_flexion_r', 'cmc_abduction_r', 'mp_flexion_r', 'ip_flexion_r', 'mcp2_flexion_r', 'mcp2_abduction_r', 'pm2_flexion_r', 'md2_flexion_r', 'mcp3_flexion_r', 'mcp3_abduction_r', 'pm3_flexion_r', 'md3_flexion_r', 'mcp4_flexion_r', 'mcp4_abduction_r', 'pm4_flexion_r', 'md4_flexion_r', 'mcp5_flexion_r', 'mcp5_abduction_r', 'pm5_flexion_r', 'md5_flexion_r', 'sternoclavicular_r2_l', 'sternoclavicular_r3_l', 'unrotscap_r3_l', 'unrotscap_r2_l', 'acromioclavicular_r2_l', 'acromioclavicular_r3_l', 'acromioclavicular_r1_l', 'unrothum_r1_l', 'unrothum_r3_l', 'unrothum

In [46]:
# number of actuators, we don't have any because no muscles
model.na 

0

In [47]:
data.act 
#action vector (muscle activations or actuator commands).

array([], dtype=float64)